Napisala rešitev za nalogo maphija
jaanos/or-zbirka pull request #32
Opened 2020-04-18 10:04 UTC by zalastopar

Co-authored-by: Jure Babnik <https://github.com/Babnik21>

2020-04-18 12:45 UTC, jaanos requested changes
Tukaj je rešitev za nalogo `tovarna`, tako da sem preimenoval pull request.

@zalastopar in @Babnik21, prosim vaju, da se držita [smernic](https://github.com/jaanos/or-zbirka/blob/master/STRUCTURE.md#drugo) za pisanje. Posebej bi opozoril na sledeče:
* Za ločilo decimalk se uporablja pika (`.`).
* Za ločilo tisočic se uporablja kratek presledek (`\,` v matematičnem načinu).
* Če imata v izračunu enoto (npr. €), jo uporabita na ustreznih mestih v celotnem izračunu in ne samo v rezultatu.

Spremembe seveda delajta v veji `zalastopar-operacijske-tovarna`.

Še to: če uporabljata značko `Co-authored-by`, je potrebno navesti e-poštni naslov, npr.
```
Co-authored-by: Jure Babnik <jure.babnik@gmail.com>
```

2020-04-18 12:45 UTC, jaanos commented on naloge/tovarna.tex
> +\end{itemize}
Tukaj bo bolje, če uporabita `align*`, npr.
```LaTeX
\begin{align*}
X &\dots \text{strošek} \\
...
\end{align*}
```

2020-04-18 12:45 UTC, jaanos commented on naloge/tovarna.tex
> +E(X|E) = 0,7 \cdot 800 + 0,2 \cdot 1150 + 0,1 \cdot 1500 = 940 €
Namesto `|` raje uporabita `\mid`.

2020-04-18 12:45 UTC, jaanos commented on naloge/tovarna.tex
> +\end{align*}
Strošek 350€ se nanaša na popravilo že sestavljenega izdelka *B*, tako da ga tukaj ne upoštevajta.

2020-04-18 12:45 UTC, jaanos commented on naloge/tovarna.tex
> +\end{itemize}
Namesto, da ločita primere, raje napišita pogojne verjetnosti za *C*. *X* je slučajna spremenljivka, tako da ji ne moremo kar pripisati vrednosti - dovolj bodo pogojne pričakovane vrednosti (iz izračunov je razvidno, kakšne so pogojne porazdelitve za *X*).

Pri tem poskrbita, da so enačaji poravnani. Če želita poravnati dva enačaja, lahko uporabita `\begin{alignat*}{2}`, npr. kot spodaj:
https://github.com/jaanos/or-zbirka/blob/55d47e9968d1ad270b04918e563a4b7c1664924c/naloge/letalskekarte.tex#L37-L41

2020-04-19 00:05 UTC, jaanos commented on naloge/tovarna.tex
> +\end{itemize}
Še to: če je okvarjena več kot ena komponenta, potem bomo kljub pregledu naključne komponente vedno imeli okvarjen izdelek *B*, katerega popravilo stane 350€ (ne glede na število okvarjenih komponent).

2020-04-19 11:15 UTC, zalastopar commented
Tukaj imam vprašanje. Če so pokvarjene tri komponente in pregledamo
pokvarjeno kompomento A imamo še dve pokvarjeni komponenti, ki pa jih ne
bomo zamenjali in je strošek popravila 2x 350 (ker imamo dve okvarjeni
komponenti B)+ pregled enega izdelka? Oz. če pokvarjenega izdelka me
pregledamo je strošek 3x350 + pregled enega izdelka. Vsaj tako sva midva
razumela. Če je strošek popravila izdelkov B ne glede na število
popravljenih enak 350 bi bilo to mogoče smiselno poudariti v navodilih,
kjer piše, da gre ena komponenta A v en B ter da jenstrošek poravila
izdelka B enak 350.


V ned., 19. apr. 2020 02:05 je oseba Janoš Vidali <notifications@github.com>
napisala:

> *@jaanos* commented on this pull request.
> ------------------------------
>
> In naloge/tovarna.tex
> <https://github.com/jaanos/or-zbirka/pull/32#discussion_r410776208>:
>
> > +$$
>
> +Če dobljena stroška primerjamo, lahko vidimo, da bima podjetje manjši strošek, če ne pregleda nobenega dobavljenega izdelka.
>
> +
>
> +\item Strošek za pregled vseh komponent je enak, kot v primeru (a) in sicer $940$. \\
>
> +Izračunajmo še pričakovani strošek, če tovarna pogleda eno naključno komponento. Priblem ločimo na tri dele: imamo $1$ pokvarjen izdelek, $2$ pokvarena ali $3$. Vsakega od teh primerov ločimo še na dva dela: ali izberemo pokvarjen izdelek ali ne.
>
> +\begin{itemize}
>
> +
>
> +\item[] $D_1$:
>
> +\begin{align*}
>
> +&P(C)  = \frac{1}{10} &X &= 45 €\\
>
> +&P(\neg C) = \frac{9}{10} & X &= 45 + 350 = 395 €\\
>
> +&E(X|D_1)= \frac{1}{10} \cdot 45 + \frac{9}{10} \cdot 395 =  360 €
>
> +\end{align*}
>
> +\item[] $D_2: E(X|D_2) = \frac{2}{10} \cdot 395 + \frac{8}{10} \cdot 745 = 675 €$
>
> +\item[] $D_3: E(X|D_3) = \frac{3}{10} \cdot 745 + \frac{7}{10} \cdot 1095 = 990 €$
>
> +\end{itemize}
>
>
> Še to: če je okvarjena več kot ena komponenta, potem bomo kljub pregledu
> naključne komponente vedno imeli okvarjen izdelek *B*, katerega popravilo
> stane 350€ (ne glede na število okvarjenih komponent).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jaanos/or-zbirka/pull/32#discussion_r410776208>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL7YP7NAPATMRFKIRA2LDBTRNI55PANCNFSM4MLJIKYA>
> .
>

2020-04-19 14:09 UTC, jaanos commented
Se strinjam, da bi bilo najbolje dodati v navodila pojasnilo, da je cena popravila enaka ne glede na število okvarjenih komponent - lahko to kar sama naredita.

Sicer pa očitno naloga ni najbolje zastavljena, saj je že v štartu vsak izdelek okvarjen in je najugodnejša možnost, da se ga enostavno popravi brez predhodnega pregledovanja komponent (česar pa naloga sploh ne ponudi kot možnost).

2020-04-19 18:36 UTC, jaanos commented
Commit s popravkom navodila je šel v vejo `master`, tako da se ni pojavil tukaj in sem zato naredil *cherry-pick*. @zalastopar, kot rečeno v #31, prosim, če odpreš še pull request iz veje `zalastopar-maphija`, da lahko naredim isto za preostale commite.

Prosim, če bodoče commite delata na ustrezni veji. V VS Code trenutno vejo vidita v desnem spodnjem kotu - če klikneta tja, lahko preklopita na drugo vejo.

/CC @Babnik21

2020-04-20 15:26 UTC, jaanos commented
Se opravičujem, sem očitno narobe prebral besedilo naloge - je bilo v redu rešeno že v prvo. Sem tako  popravke vnesel v različico iz 9fb3105.

2020-04-20 16:47 UTC, jaanos approved these changes

2020-04-20 16:49 UTC, merged