3.22.
jaanos/or-zbirka pull request #38
Opened 2020-06-13 13:04 UTC by mperbil

Pozdravljeni,
pošiljam nalogo 3.22.. Upam, da je napisana pravilno.
Lep pozdrav,
Maks Perbil

2020-06-16 19:59 UTC, jaanos requested changes
Sem pogledal tvojo rešitev - večinoma izgleda v redu (bo potrebno sicer popraviti nekaj številk), vseeno pa bo potrebno rešitev nekoliko razširiti - glej posamezne komentarje.

Drevo sem že nekoliko spreminjal, da se naloga prevede - da se ne prevede, lahko vidiš, ker se je pojavil križec zraven commita 49f964b. Seveda pa je najbolje, da poskusiš sam pri sebi prevajati - v ta namen lahko uporabiš datoteko [`test.tex`](https://github.com/jaanos/or-zbirka/blob/master/test.tex.template).

2020-06-16 19:59 UTC, jaanos commented on naloge/fenko.tex
> +E(X \mid  guld = 1, granodiorit = 4kg) &= 0.4 \cdot 17 G + 0.6 \cdot 5 G &&= 14.33 G \\
Tale izračun ne izgleda pravilen.

Mimogrede, če v matematičnem načinu vključuješ besedilo (vključno z enotami), ga postavi znotraj `\text{...}`. Sicer pa bo bolje, če pred izračuni uvedeš spremenljivke, npr.

* *X* ... število guldov po drugi noči
* *Y_i* ... število guldov pred *i*-to nočjo (*i* = 1, 2)
* *Z_i* ... kilogrami granodiorita pred *i*-to nočjo (*i* = 1, 2)

Tako enote v izračunih ne bodo potrebne, jasno pa bo postalo tudi, zakaj je način izračuna pričakovane vrednosti drugačen za drugo noč v primerjavi s prvo. Da bo uvajanje spremenljivk lepo izgledalo, lahko narediš podobno kot tukaj:

https://github.com/jaanos/or-zbirka/blob/39627640b39134fda6253fa2b1753b0d1afe4b25/naloge/tovarna.tex#L31-L38

2020-06-16 19:59 UTC, jaanos commented on slike/fenko.tikz
> +\node      (P) at ( 8, 6) {$17$};
Ponekod imaš napisane enote, drugod pa ne - to poenoti (morda bi na drevesu bilo smiselno pustiti enote). Oznake pri vozliščih (za pričakovane vrednosti pri vozliščih) so tukaj postavljene s koti - ker so te dovolj kratke, bo lepše izgledalo, če jih postaviš nad ali pod vozlišče (namesto kota uporabi `above` ali `below` - načeloma bi lahko uporabil tudi `left` ali `right`). Potrebno bo tudi popraviti oznake pri odločitvi pred drugo nočjo (te bodo seveda enake oznakam pri izbrani veji).

2020-06-16 19:59 UTC, jaanos commented on slike/fenko.tikz
> +\draw (E) -- (J) node[below, midway, sloped] {kupi 0 kg};
Načeloma so tukaj še vmesne možnosti (kupi 1, 2, 3 kg), vendar se strinjam, da bi bilo drevo v tem primeru nepregledno. Namesto tega v besedilu naloge raje utemelji, zakaj pride v upoštev samo nakup maksimalne količine granodiorita - v splošnem izračunaj E(*X* | *Y_2* = *k-2x*, *Z_2* = *x*), kjer je *k* število guldov po prvi noči in *x* število kilogramov kupljenega granodiorita pred drugo nočjo.

2020-06-16 19:59 UTC, jaanos commented on naloge/fenko.tex
> +E(X \mid  guld = 1, granodiorit = 2kg) &= 0.4 \cdot 14.33 G + 0.6 \cdot 3.3 G &&= 7.65 G \\
Tukaj bo potrebno popraviti oba podatka iz zgornjih izračunov.

2020-06-18 12:01 UTC, mperbil commented
Pozdravljeni,
popravil sem vse kar ste napisali, vendar pa imam problem s prevajanjem, saj se mi ne prevede.
Lep pozdrav,
Maks Perbil

2020-06-18 16:57 UTC, jaanos requested changes
Svetujem, da dodaš še malo besedila, da se bo rešitev lepše brala. Najprej torej poveš, da boš uvedel slučajne spremenljivke *X*, *Y*<sub>*i*</sub>, *Z*<sub>*i*</sub>, jih uvedeš, nato poveš, da boš obravnaval odločitev pred drugo nočjo glede na trenutno število guldov *k* (kjer opaziš, da se izplača kupiti maksimalno količino granodiorita), nato pa greš šele računat pričakovane vrednosti za drugo noč (pred tem pojasniš, katere vrednosti *k* in *x* si uporabil in zakaj) in nazadnje še za prvo noč.

2020-06-18 16:57 UTC, jaanos commented on slike/fenko.tikz
> +\node[dec] (H) at ( 0, -8) [label=left:$3$ G, kupi $2$ kg] {};
Kolikor vidim, je problem tukaj - Ti*k*Z razume vejico kot ločilo polj, zato pride do napake (če bi jo hotel imeti kot oznako vozlišča, bi moral vse skupaj oviti v zavite oklepaje). Sicer pa to ni mesto za pisanje odločitev - v oznakah vozlišč naj bodo pričakovane vrednosti v teh vozliščih (ker gre za odločitvena vozlišča, bo torej oznaka enaka kot pri izbrani veji).

Mislim tudi, da bo vendarle izgledalo lepše, če so te oznake nad ali pod vozlišči (enako tudi pri slučajnih dogodkih za drugo noč).

2020-06-18 16:57 UTC, jaanos commented on naloge/fenko.tex
> +E(X \mid  Y_1 = 3, Z_2 = 1) &= 0.4 \cdot 7.6 + 0.6 \cdot 4.4 &&= 5.68 \\
Tukaj bo potrebno uporabiti *Z*<sub>1</sub>.

2020-06-20 17:43 UTC, mperbil commented
Pozdravljeni,
popravil sem kar ste napisali, tudi slika se sedaj prevede, še zmeraj pa se ne prevede fenko.tex.
Lep pozdrav,
Maks Perbil

2020-06-21 11:21 UTC, jaanos commented
Hvala za rešitev in dopolnitev! Problem je bil v tem, da podpisovanje ne delue izven matematičnega načina, kamor tako ali tako sodijo vse spremenljivke. Sem popravil in še nekoliko uredil rešitev.

2020-06-21 11:22 UTC, jaanos approved these changes

2020-06-21 11:25 UTC, merged