Resitev naloge 5.27
jaanos/or-zbirka pull request #54
Opened 2021-06-03 17:54 UTC by juresternad

2021-06-05 16:35 UTC, jaanos requested changes
Hvala @juresternad za rešitev. Bi te pa prosil še za nekaj popravkov.

Pri trenutni rešitvi si prilagodil Floyd-Warshallov algoritem tako, da vrne negativen cikel, ko ga najde. Težava je v tem, da ni nujno, da je tak negativen cikel dejansko dosegljiv iz začetnega vozlišča - pa tudi če je, algoritem morda take poti še ni obravnaval (tj., vsebuje vozlišče, ki ga glavna zanka algoritma še ni obiskala). Če bi ostal pri trenutnem pristopu, bi torej bilo potrebno ob najdbi negativnega cikla preveriti, ali je ta dosegljiv iz začetnega vozlišča, in samo v tem primeru končati.

Glede na to, da je začetno vozlišče fiksno, bi pa bilo bolj učinkovito, če bi namesto Floyd-Warshallovega uporabil Bellman-Fordov algoritem: podobno kot pri [nalogi na kolokviju](https://github.com/jaanos/or-zbirka/blob/52df17cf7ccc6de79a1cb676256c8ea3b82724ab/naloge/najvect.tex) ga bo potrebno prilagoditi tako, da se predniki beležijo za vsak korak glavne zanke posebej (tj., prednik iz prejšnjega koraka se ne prepiše, ko najdeš krajšo pot z več povezavami). Tako bo mogoče rekonstruirati tudi poti, ki vsebujejo cikle.

Algoritem, ki si ga napisal, izgleda pythonovsko - če pogledaš druge algoritme v zbirki, so napisani tako, da ne spominjajo na kakšen konkreten programski jezik. Zato svetujem, da kar skopiraš trenutno različico [Bellman-Fordovega algoritma](https://github.com/jaanos/or-zbirka/blob/297d8175fa8738a5d128e609f444f6e144fe55ce/naloge/bf.tex) (sem ga nekoliko predelal, tako da je bližje temu, kar smo naredili na vajah) in ga dopolniš (obstoječih spremenljivk ne preimenuj). Da bo v skladu z ostalimi algoritmi v zbirki, funkcijo poimenuj kar `MaksimalniDobiček`.

Še ena stvar glede algoritma: v takih algoritmih (pa tudi na splošno pri dinamičnem programiranju) nikoli ne hranimo celotnih poti, pač pa samo predhodnike (oziroma izbiro, ki je pripeljala do končnega rezultata); iz teh informacij lahko na koncu rekonstruiramo želene poti. Razlog je ta, da hranjenje poti (npr. v seznamu) prinese dodatno delo zaradi kopiranja podatkov v vsakem koraku - ker so poti lahko dolge O(*n*), je časovna zahtevnost tvojega algoritma v resnici O(*n*<sup>4</sup>) (mimogrede, velik O je pomemben: o(*n*<sup>3</sup>) pomeni "asimptotično strogo manj kot *n*<sup>3</sup>").

Trenutno si tudi skonstruiral pomožen graf, a če pogledaš drugod, vidiš, da so grafi povsod neuteženi ter da so uteži podane posebej. Tako ne bo potrebno skonstruirati pomožnega grafa - lahko bi skonstruiral pomožne (negirane) uteži, a glede na to, da bo treba prilagoditi sam algoritem, bo bolje, če enostavno deluje z danimi utežmi in namesto najcenejše išče najddražjo pot.
Kar se tiče izhoda, bi bilo smiselno vračati tri stvari: zaslužek (neskončen, če je dosegljiv pozitiven cikel), najdražjo pot (ali pot do pozitivnega cikla), in sam pozitiven cikel (ali pa `\Null`, če ta ne obstaja). Poti lahko rekonstruiraš tako, da prirediš funkcijo `RekonstruirajPot` iz naloge [`topo`](https://github.com/jaanos/or-zbirka/blob/master/naloge/topo.tex) - najbolje, da jo imaš kot pomožno funkcijo. V primeru, da najdeš pozitiven cikel, boš dobil pot dolžine \|*V*\| (ne nujno do vozlišča na ciklu!) - v njej bo torej potrebno poiskati prvo vozlišče, ki se ponovi, ter tako dobiš pot do cikla in sam cikel.

2021-06-06 23:56 UTC, jaanos requested changes
Tukaj je še nekaj popravkov in predlogov.

2021-06-06 23:56 UTC, jaanos commented on naloge/poslovnez.tex
> +\Function{MAKSIMALNIDOBIČEK}{$G = (V, E), s \in V, L : E \to \R$}
Imena funkcij piši v CamelCase, npr. `MaksimalniDobiček`.
```suggestion
\Function{MaksimalniDobiček}{$G = (V, E), s \in V, L : E \to \R$}
```

2021-06-06 23:56 UTC, jaanos commented on naloge/poslovnez.tex
> +            \State \Return graf ima negativen cikel
Kot rečeno, bo tukaj treba dobiti pot do nekega vozlišča in iz nje izluščiti cikel in pot do njega.

2021-06-06 23:56 UTC, jaanos commented on naloge/poslovnez.tex
> +        \For{$uv \in E$}
Glede na to, da imaš množico `trenutna`, bo zadostovalo, da greš čez vozlišča v njej in čez sosede vsakega od njih.

2021-06-06 23:56 UTC, jaanos commented on naloge/poslovnez.tex
> +    \State $konec \gets \{v | d_{i,v}= zasluzek \}$
Tole bi se lepše zapisalo tako:
```LaTeX
    \State $(\text{\sl zaslužek}, \text{\sl konec}) \gets \max\{(d[i][u], u) \mid i = 0, 1, \dots, |V|, \ u \in V\}$
```
Morda pa bo še bolje, če si kar sproti (vsakič, ko poračunaš novo razdaljo) beležiš največjo razdaljo ter ustrezno vozlišče in globino (`i`), tako da ti jih ni potrebno iskati tukaj.

2021-06-06 23:56 UTC, jaanos commented on naloge/poslovnez.tex
> +        \While{$i \ne 0$}
Spremenljivka `i` ni nikjer definirana - najbolje, da jo podaš kar kot parameter funkcije, saj je števila povezav v njej ne poznaš vnaprej.

Pazi tudi, da zajameš vsa vozlišča - ustreznejši pogoj bi bil `i \ge 0`.
```suggestion
        \While{$i \ge 0$}
```

2021-06-06 23:56 UTC, jaanos commented on naloge/poslovnez.tex
> +    \State $\pred \gets$ seznam slovarjev z vrednostjo $\Null$
Tukaj naj bo jasno, kako indeksiraš sezname - piši torej `d[0, \dots, n]` in podobno za `\pred`, kjer lahko pravzaprav začneš z `1`.
```suggestion
    \State $d[0, \dots, n] \gets$ seznam slovarjev z vrednostjo $-\infty$ za vsako vozlišče $v \in V$
    \State $\pred[1, \dots, n] \gets$ seznam slovarjev z vrednostjo $\Null$
```

2021-06-06 23:56 UTC, jaanos commented on naloge/poslovnez.tex
> +    \State \Return $(zasluzek,$ RekonstruirajPot $(pred,konec)$, $\Null$)
```suggestion
    \State \Return $(zasluzek, \text{\sc RekonstruirajPot}(\pred, \text{\sl konec}), \Null)$
```
Pri klicu `RekonstruirajPot` bo potrebno dodati še globino (glej spodaj).

2021-06-07 17:48 UTC, juresternad commented
Najlepša hvala za vse predloge in razlage posameznih napak. Ko sem začel z nalogo, sem poskušal narediti rešitev s pomočjo BF algoritma, vendar mi v Pythonu ni uspelo napisati kode in zato sem se odločil za uporabo FW algoritma. Hvala tudi za predelavo BF algoritma. 

Ko sem včeraj "pushal" na repozitorij, nisem vedel, da se bo avtomatsko aktiviral ukaz "Merge branch", saj verzija ni bila še namenjena vam v pregled, tako da se opravičujem za dodatno delo.

Mislim, da so v zadnji verziji popravljene vse naštete napake, morda je potrebno popraviti še kaj pri notaciji.

Ko sem zagnal testno datoteko, mi ta ni prevedla ukaza "naloge~\res[topo]". Verjetno gre za problem testne datoteke, saj sem zasledil, da je v ostalih nalogah uporabljen navedeni ukaz.

2021-06-08 12:00 UTC, jaanos approved these changes

2021-06-08 12:28 UTC, jaanos commented
@juresternad, hvala za popravke in seveda celotno rešitev. Sem še malo uredil besedilo in algoritem, da bo lepše berljivo in da se bo dalo na `RekonstruirajPot` sklicevati v rešitvi naloge s kolokvija.

Sicer pa, vsakič, ko narediš push na vejo, iz katere je aktiven pull request, se ta posodobi (verjetno si tudi sam dobival obvestila, ko sem sam naredil kak commit). Sicer pa z vmesnim pregledom nisem imel dodatnega dela - jasno mi je bilo, da to še ni končna različica, nekatere komentarje pa bi verjetno imel pri naslednjem pregledu.

Kar se pa tiče ukaza `\res`, bi moral delovati v testni datoteki, saj je tam tudi definiran:
https://github.com/jaanos/or-zbirka/blob/1b31983e0f6f863cc8218b1c1d1edf52b5f297c4/test.tex.template#L11
Če si to vrstico po nesrečii pobrisal, pa jo seveda lahko vrneš (ali pa kar skopiraš vzorec in popraviš samo ime naloge).

2021-06-08 12:28 UTC, merged

2021-06-08 13:00 UTC, juresternad commented
@jaanos sem pregledal in opazil izboljšave. Opazil sem tudi popravke pri datoteki [slike/poslovnez-osnova.tikz](https://github.com/jaanos/or-zbirka/blob/master/slike/poslovnez-osnova.tikz). Slike sem tako poskušal narediti že pri prvi verziji rešitve, a sem očitno pozabil definirati `\NewEnviron{usmerjen@poslovnez}{`.  Za ukaz `\res ` sem preveril in zdaj deluje.

Še enkrat hvala za vso pomoč.